# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages
dist: trusty
r_github_packages: ipums/ipumsr/ipumsexamples

matrix:
  include:
    - r: release
      env: cache_type=v1
    - r: oldrel
      env: cache_type=v2
    - r: devel
      env: cache_type=v3
    - r: 3.2
      env: cache_type=v4

before_install:
    - Rscript -e 'if (R.version$major == "3" & as.numeric(R.version$minor) >= 5) install.packages("devtools")'
    - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
    - sudo apt-get --yes --force-yes update -qq
    - sudo apt-get install --yes libproj-dev libgeos-dev libgdal-dev libudunits2-dev
    - Rscript -e 'if (Sys.getenv("TRAVIS_R_VERSION_STRING") == "3.2") install.packages("jsonlite")'

after_success:
  - Rscript -e 'if (!(R.version$major == "3" && substr(R.version$minor, 1, 1) == "2")) covr::codecov()'

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
